### ISSUE TITLE
[RFE] Add an option to show only the latest microcode available for a CPUID

### ISSUE THREAD

**Issue by L-B** [platomav/MCExtractor#21]
Hello,

First, thank you for that invaluable tool, it's quite helpful in handling this year's string of vulnerabilities.
My goal is to automate a check of a number of systems to see if they're running the latest available microcode. Getting the CPUID and running `MCE -search <cpuid> -redir` gives the full list in a formatted way.
I would like to know if it's possible to add an option that would return only the most recent version for that microcode, or maybe the same list, but more easily parseable in a script (without the header and table, and with a field separator).

**Comment by L-B** [comment]
Hello,

Let me explain: I've got a bunch of servers to keep up to date for security. To patch, it's both via HPE s BIOS updates and RHEL microcode upgrades. However, this year's flurry of activity is causing confusion (eg, microcode updates pushed then pulled then pushed again, HPE updates being delivered in September but dated from May and containing microcodes released by Intel in August, RHEL still on the July release because their QA is long...).
n short, I only want to use MCE to compare the microcode running on the systems (pulled from /proc/cpuinfo) to the latest known version:
 - get CPUID
 - get microcode version
 - compare microcode version with the latest in MCE's database for that CPUID
 - return an alert if different

I think the Blob format won't help for that, but thanks for pointing it out anyway, I do think it can be useful!

**Comment by platomav** [comment]
Ah so you want to basically search the MCE DB. There are two possibilities in such case:

* If you only want (or have access to) the CPUID & Version, it would be much easier for you to search the DB file directly, which is in the well known SQLite format.

* If you can additionally get the Platform IDs of the currently loaded microcode (MSR 0x17), then you should use MCE which will intelligently detect the latest microcode for that system. Check the last bullet point of the [repositories readme](https://github.com/platomav/CPUMicrocodes) to understand why that is important. This option will require some changes and a new parameter in MCE. Note that in this case, MCE needs the loaded microcode's Platform IDs (i.e. 0x5C = 2,3,4,6) and not the system's (i.e. 4).

**Comment by L-B** [comment]
You're right, it could be easier to do a small SQLite request. I'll look into that.
The platorm ID is a problem, I've not found how to get it, the content of /proc/cpuinfo is incomplete, and I couldn't find it in `cpuid` or `lscpu` either.
I'm targeting only RHEL6/7 so far. I don't believe there's a way to dump the microcode there, I've not found one at least.

**Comment by platomav** [comment]
Alright, I added support for what you're looking for. MCE is built around analyzing inputted microcode binaries which have all the relevant info so it required a lot of work to detect the latest microcode with only CPUID, Version & Platform. Here is what needs to be done:

`dmesg | grep microcode`

Then you run "MCE -last CPUID Version Platform" and it should report Yes or No on whether the microcode is latest and if not, it will also print the latest microcode.

![screenshot from 2018-09-11 20-56-10](https://user-images.githubusercontent.com/11527726/45378480-3a5c8100-b606-11e8-87f6-2ff9c424256f.png)

Note that the Platform reported by dmesg is the actual platform's ID, not the loaded microcode's IDs. In the example above, you can see that the actual 206A7 microcode has Platform IDs 0x12 = 1,4 but dmesg reported 0x10 = 4 because that's what the system supports. Some other system could report 0x2 = 1 and that would also be ok for the microcode binary's 0x12 = 1,4 supported platforms.

As for the output, another solution is to not print Yes/No but instead return code 0 for Yes and 1 for No or something.

Let me know what you think and if the aforementioned solution covers you, I can push a new commit.

**Comment by platomav** [comment]
https://github.com/platomav/MCExtractor/commit/b76c73da646724d5d4fc4545880f32bc0bee039c
