### ISSUE TITLE
Missing installation instructions for libraries under linux

### ISSUE THREAD

**Issue by eNTi** [platomav/MCExtractor#6]
I had to install "macholib" as well as "pefile" to satisfy all build dependencies.

**Comment by platomav** [comment]
The dependencies shown at the Readme are indicative of the actual external (3rd-party) imports done by MCE. Any other python or OS-specific modules should be collected by the freeze tools such as PyInstaller, Py2Exe etc. I added support for Linux and MacOS back in February (v1.3.0) and but I haven't checked it since because I don't use those platforms actively. It should work though and at the time, I did verify that I was able to build & run MCE in Ubuntu via PyInstaller, without any problems.
