### ISSUE TITLE
Microcode Updates

### ISSUE THREAD

**Issue by zaolin** [platomav/MCExtractor#9]
Hey platomav,

I am a coreboot developer and would like to ask if it is possible to share microcode
updates in a different way, e.g. git repository. Currently you use mediafire which works not
really good for our project. We already have a git blobs repository. Are there any issues with
licenses ?

Best Regards, Philipp

**Comment by platomav** [comment]
Hey Philipp,

I'm not really accustomed to git repositories outside of the basic github features that I use for my projects and  I'm not certain how that would work when we're talking about 450 files or so at this point. And if I ever add older versions to the repos (not just Latest), that would mean 1500 or more. A more important issue are licenses which is a big unknown for now. Technically, vendors give all microcodes to OEMs and then we extract them from the latter's BIOS/UEFI images so that other systems (which are not so lucky) can get updated manually too. I don't believe Intel, AMD and VIA will care, as long as only Production microcodes are shared to the community. But it's early and that's just wishful thinking.

**Comment by titanous** [comment]
+1 to hosting these on GitHub, it should be no problem. Just make a new repo and `git add` the individual files (not the rar), add a README, and commit/push. There is no licensing difference between uploading to GitHub and uploading to another site, and you don't need to create a LICENSE file.

**Comment by platomav** [comment]
**Update:**

https://github.com/platomav/CPUMicrocodes

**Comment by zaolin** [comment]
Thanks! That helps a lot!
